"""
scripts/materialize_parameter_overlay.py
=========================================
Materialize APPROVED_FOR_REPLAY parameter proposals into a YAML overlay config.

Rules
-----
- Only parameter proposals with status == APPROVED_FOR_REPLAY are processed.
- Strategy proposals are explicitly ignored, regardless of status.
- Dotted parameter names (e.g. "structuring.dte_min") are rendered as nested YAML.
- When two proposals target the same parameter, the one with higher confidence wins.
  A warning is printed for each duplicate resolved this way.
- Writes NEVER touch production config files (configs/*.yaml).
  Output is written only to configs/overlays/ (or --out-dir if specified).
- --dry-run prints the YAML to stdout without writing any files or updating proposals.

Usage
-----
    python scripts/materialize_parameter_overlay.py [options]

Options
-------
    --proposals PATH   Managed proposals store.
                       Default: runs/proposals/weekly_reflection_proposals.json
    --out-dir PATH     Output directory for overlay YAML.
                       Default: configs/overlays/
    --dry-run          Print overlay YAML to stdout; do not write files.
"""
from __future__ import annotations

import argparse
import sys
import warnings
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

_SCRIPTS_DIR = Path(__file__).parent
PROJECT_ROOT = _SCRIPTS_DIR.parent
sys.path.insert(0, str(PROJECT_ROOT))

import yaml  # pyyaml — required dependency (pyyaml>=6.0 in requirements.txt)

from forecast_arb.ops.proposals import load_proposals, save_proposals

_DEFAULT_PROPOSALS = Path("runs/proposals/weekly_reflection_proposals.json")
_DEFAULT_OUT_DIR = Path("configs/overlays")


# ---------------------------------------------------------------------------
# Internal helpers (testable)
# ---------------------------------------------------------------------------


def _load_and_filter(proposals_path: Path) -> List[dict]:
    """
    Load the managed proposals store and return only APPROVED_FOR_REPLAY
    parameter proposals.

    Strategy proposals are silently skipped.
    """
    proposals_path = Path(proposals_path)
    container = load_proposals(proposals_path)
    return [
        p for p in container.get("proposals", [])
        if p.get("type") == "parameter" and p.get("status") == "APPROVED_FOR_REPLAY"
    ]


def _dedup_by_parameter(proposals: List[dict]) -> List[dict]:
    """
    Deduplicate proposals by parameter name.

    When multiple proposals target the same parameter, the one with the
    highest confidence is kept. A warning is printed to stderr for each
    collision resolved.

    None confidence is treated as 0.0 for comparison purposes.
    """
    by_param: Dict[str, dict] = {}
    for p in proposals:
        param = p.get("parameter", "")
        if not param:
            continue
        existing = by_param.get(param)
        if existing is None:
            by_param[param] = p
        else:
            existing_conf = existing.get("confidence") or 0.0
            new_conf = p.get("confidence") or 0.0
            if new_conf > existing_conf:
                print(
                    f"[materialize] WARNING: duplicate parameter {param!r} — "
                    f"keeping id={p['id']!r} (confidence={new_conf:.2f}) over "
                    f"id={existing['id']!r} (confidence={existing_conf:.2f})",
                    file=sys.stderr,
                )
                by_param[param] = p
            else:
                print(
                    f"[materialize] WARNING: duplicate parameter {param!r} — "
                    f"keeping id={existing['id']!r} (confidence={existing_conf:.2f}) over "
                    f"id={p['id']!r} (confidence={new_conf:.2f})",
                    file=sys.stderr,
                )
    return list(by_param.values())


def _build_overlay_dict(proposals: List[dict]) -> Dict[str, Any]:
    """
    Build a nested dict from the deduplicated proposals.

    Dotted parameter names are expanded into nested dicts:
        "structuring.dte_min" → {"structuring": {"dte_min": <value>}}
    """
    root: Dict[str, Any] = {}
    for p in proposals:
        param = p.get("parameter", "")
        value = p.get("suggested_value")
        if not param:
            continue
        parts = param.split(".")
        node = root
        for part in parts[:-1]:
            node = node.setdefault(part, {})
        node[parts[-1]] = value
    return root


def _render_yaml(
    overlay_dict: Dict[str, Any],
    proposals_path: Path,
    ts_utc: str,
) -> str:
    """Render the overlay dict as a YAML string with a header comment block."""
    header_lines = [
        "# Generated by materialize_parameter_overlay.py",
        f"# Source: {proposals_path}",
        f"# Materialized: {ts_utc}",
        "# TEST OVERLAY ONLY — never applied to production config automatically.",
        "# Review and apply manually after validation.",
        "",
    ]
    body = yaml.dump(overlay_dict, default_flow_style=False, sort_keys=True)
    return "\n".join(header_lines) + body


def _run(
    proposals_path: Path,
    out_dir: Path,
    dry_run: bool,
) -> int:
    """
    Core logic: filter, dedup, build, render, and optionally write.

    Returns:
        0 on success (including no-op when no qualifying proposals).
        1 on unexpected error.
    """
    proposals_path = Path(proposals_path)
    out_dir = Path(out_dir)

    # Load qualifying proposals
    qualifying = _load_and_filter(proposals_path)

    # Report skipped strategy proposals for operator awareness
    container = load_proposals(proposals_path)
    strategy_reviewed = [
        p for p in container.get("proposals", [])
        if p.get("type") == "strategy"
        and p.get("status") not in ("PENDING", "REJECTED")
    ]
    if strategy_reviewed:
        print(
            f"[materialize] NOTE: {len(strategy_reviewed)} reviewed strategy proposal(s) "
            "are excluded — strategy proposals cannot be materialized into overlays.",
            file=sys.stderr,
        )

    if not qualifying:
        print(
            "[materialize] No APPROVED_FOR_REPLAY parameter proposals found. "
            "Nothing to materialize.",
            file=sys.stderr,
        )
        return 0

    # Dedup
    deduped = _dedup_by_parameter(qualifying)

    # Build overlay
    overlay_dict = _build_overlay_dict(deduped)
    if not overlay_dict:
        print("[materialize] Overlay dict is empty after building. Nothing to write.", file=sys.stderr)
        return 0

    ts_utc = datetime.now(timezone.utc).isoformat()
    yaml_text = _render_yaml(overlay_dict, proposals_path, ts_utc)

    if dry_run:
        print(yaml_text)
        print(
            f"[materialize] --dry-run: would have materialized {len(deduped)} proposal(s).",
            file=sys.stderr,
        )
        return 0

    # Write overlay file
    out_dir.mkdir(parents=True, exist_ok=True)
    ts_filename = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S")
    overlay_path = out_dir / f"{ts_filename}_reflection_test.yaml"
    overlay_path.write_text(yaml_text, encoding="utf-8")
    print(f"[materialize] Wrote overlay → {overlay_path}")

    # Update overlay_path on materialized proposals in the store
    overlay_path_str = str(overlay_path.resolve())
    updated_container = load_proposals(proposals_path)
    materialized_ids = {p["id"] for p in deduped}
    for p in updated_container.get("proposals", []):
        if p.get("id") in materialized_ids:
            p["overlay_path"] = overlay_path_str
    save_proposals(proposals_path, updated_container)

    print(
        f"[materialize] Materialized {len(deduped)} parameter proposal(s). "
        f"overlay_path recorded in proposals store."
    )
    return 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description=(
            "Materialize APPROVED_FOR_REPLAY parameter proposals into a YAML overlay. "
            "Strategy proposals are always excluded. "
            "Never modifies production configs."
        ),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument(
        "--proposals", type=Path, default=_DEFAULT_PROPOSALS,
        help="Path to the managed proposals JSON store.",
    )
    p.add_argument(
        "--out-dir", type=Path, default=_DEFAULT_OUT_DIR,
        help="Output directory for overlay YAML files.",
    )
    p.add_argument(
        "--dry-run", action="store_true", default=False,
        help="Print overlay YAML to stdout; do not write files or update proposals.",
    )
    return p


def main() -> None:
    args = _build_parser().parse_args()
    rc = _run(
        proposals_path=args.proposals,
        out_dir=args.out_dir,
        dry_run=args.dry_run,
    )
    sys.exit(rc)


if __name__ == "__main__":
    main()
